version: "2"

run:
  tests: false

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - wastedassign
    - zerologlint
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G115
        - G406
        - G507
    staticcheck:
      checks:
        - SA*
        - -SA1019
