version: '2'

run:
  tests: false

linters:
  default: 'all'
  disable: [ 'wsl' ]
  exclusions:
    paths:
      - 'third_party'
    rules:
      - path: '^.*\.go$'
        linters:
          - 'gochecknoglobals'
          - 'intrange'
          - 'noinlineerr'
          - 'nonamedreturns'
  settings:
    cyclop:
      max-complexity: 100
    depguard:
      rules:
        main:
          allow:
            - '$gostd'
            - 'github.com/rbee3u/dpass'
            - 'github.com/spf13/cobra'
            - 'golang.org/x/crypto'
            - 'golang.org/x/term'
            - 'rsc.io/qr'
    exhaustruct:
      exclude: [ '^.*$' ]
    gosec:
      excludes: [ 'G115', 'G406', 'G507', 'G602' ]
    mnd:
      ignored-files: [ '^.*\.go$' ]
    nlreturn:
      block-size: 1000
    revive:
      rules: [ { name: 'exported', disabled: true } ]
    staticcheck:
      checks: [ "all", "-SA1019", "-ST1000" ]
    varnamelen:
      min-name-length: 1
    wsl_v5:
      default: 'none'
