name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install deps
        run: make deps
      - name: Check style
        run: make style
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Lint
        run: make lint
